### ISSUE TITLE
HP Elite X3 support

### ISSUE THREAD

**Issue by lostmsu** [SuperJMN/WoA-Installer#1]
Subj. Device even has the next gen SoC (e.g. Snapdragon 82x).

**Comment by cesar527** [comment]
Yes, it would be great to have HP Elite X3 support.

**Comment by SuperJMN** [comment]
Hello! There's no way to unlock its bootloader nor drivers for it. So, I cannot add support for it. Sorry.

**Comment by lostmsu** [comment]
@SuperJMN I am curious, if you tried doing this yourself?
