### ISSUE TITLE
Download failes if Download folder is moved

### ISSUE THREAD

**Issue by AdmJLovejoy** [SuperJMN/WoA-Installer#10]
Download fails if Downloads folder is moved. My Downloads folder was moved to D: drive and image download fails with a path not found error. If I run the cmd from the empty Downloads folder on my boot dive, all is good.

**Comment by CornyjK** [comment]
If you mean the iso downloader, that is not really an issue of this installer.

**Comment by SuperJMN** [comment]
Sorry, this doesn't apply to WoA Installer. If you need help, as us in the [LumiaWOA](https://t.me/joinchat/ACWtm0Up3wzSbWjjfxk-NA) group in Telegram :)
