### ISSUE TITLE
Win10Installer repeatedly crash

### ISSUE THREAD

**Issue by dinosauria123** [SuperJMN/WoA-Installer#2]

**Comment by dinosauria123** [comment]
18237 crashes at “ Just a moment” repeatedly.

**Comment by SuperJMN** [comment]
Hello! 
Can you give me the steps to reproduce this?

**Comment by dinosauria123** [comment]
About 10 times boot attempt, the error code was different randomly.

**Comment by dinosauria123** [comment]
I use your WoA installer for raspberry pi, booting seems to be fine.

**Comment by dinosauria123** [comment]
Do you have any recommended version of Windows10 for Arm ?

**Comment by dinosauria123** [comment]
It seems to build 18237 does not working image.

I used build 1803, It works all fine!

Thank you for your works !

**Comment by TomDobbelaere** [comment]
Just had the same with build 1809 selected on the website, trying 1803 next as per this guy's experience
