### ISSUE TITLE
Add bootaa64.efi to Core Package

### ISSUE THREAD

**Issue by Tourniquet88** [SuperJMN/WoA-Installer#6]
Builds higher than 17134 won't boot on the Lumia 950 (XL) anymore. So it would be nice if you could add support for the bootaa64.efi in your Core Package. This way we can install newer builds where the bootaa64.efi gets replaced with the one 17134 automatically.

Maybe add a manually check for it, so after updates bootaa64.efi can be replaced with it too.

**Comment by SuperJMN** [comment]
Added!
